### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by monooz23**
new collection 500 squares

### CODE REVIEW

**Comment by monooz23** [comment]
@cliobitcoinbank are you able to help me merge  this with the main collection?
not sure why checks are failing?  the json files are clear with a validatore that I use?

**Comment by monooz23** [comment]
@cliobitcoinbank are you able to help me merge this with the main collection?
not sure why checks are failing? the json files are clear with a validatore that I use?

**Review by cliobitcoinbank — COMMENTED** [review]
image

**Comment by monooz23** [comment]
So what do I do?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
