### PR TITLE
Bitcoin Bears Club Collection

### PR DESCRIPTION
**Pull request by thepantherplus**
Bitcoin Bears Club Collection Added

### CODE REVIEW

**Comment by BTCAlchemist** [comment]
@MillHaus33 @gamingcx Could you let us know if our collection is good to go?

**Comment by chrisconfirm** [comment]
is already in /btcbearsclub, (but there the numbering is different.) please wait, your collection will be updated soon.

**Comment by BTCAlchemist** [comment]
@chrisconfirm Thanks for the reply. I see Bitcoin Bears Club is live on OrdinalsWallet.com. May we merge this commit?
How may we set our golden avatar bear as the cover image? https://ordinalswallet.com/inscription/f74138a2bbd7c3fe517754245c210a0d5962c6ef38d1f6e66a6d1302aeb2ff95i0
image

**Comment by chrisconfirm** [comment]
@BTCAlchemist sorry i have to check, how do i know if this is your collection?

**Comment by BTCAlchemist** [comment]
@chrisconfirm You'll see that @thepantherplus and I are contributors to the original branch at https://github.com/thepantherplus/bitcoin-bears-club

**Comment by BTCAlchemist** [comment]
@chrisconfirm The new owner of this collection is @slavkart. They are permitted to make changes to the Bitcoin Bears Club collection details.

**Pull request merged**
