### PR TITLE
Create palindrome-punks

### PR DESCRIPTION
**Pull request by Blok905**
[inscriptions.json.json](https://github.com/ordinals-wallet/ordinals-collections/files/12908954/inscriptions.json.json)
[meta.json](https://github.com/ordinals-wallet/ordinals-collections/files/12908956/meta.json)

### CODE REVIEW

**Comment by Blok905** [comment]
[inscriptions.json](https://github.com/ordinals-wallet/ordinals-collections/files/12909025/inscriptions.json)
[meta.json](https://github.com/ordinals-wallet/ordinals-collections/files/12909026/meta.json)

**Comment by chrisconfirm** [comment]
close pr. palindrome punks already existing in /collecions/palindroms-punks/

**Comment by Blok905** [comment]
> close pr. palindrome punks already existing in /collecions/palindroms-punks/

Not sure who uploaded this - it wasnt me - I just joined github like a week ago and this was published about a month ago

I dont have permission to make changes to this collection in github

Can you update for me using the inscription.json and meta.json files I have uploaded above?

Screenshot 2023-10-18 134546

**Comment by Blok905** [comment]
Hey,

Can you please give me more detailed instructions on how to proceed? This
is my first time working on GitHub and your response was not constructive
enough to help me move my collection forward

Blok905.btc

**Pull request closed without merging**
