### PR TITLE
Add Degen Krew Ordinals Listing

### PR DESCRIPTION
**Pull request by Karmeleons**
Add initial Degen Krew inscriptions

### CODE REVIEW

**Comment by MillHaus33** [comment]
@Karmeleons are you intending to update all those collections?

**Comment by Karmeleons** [comment]
@MillHaus33 Nope, just adding in Karmz Ordinals (minted out) and Degen Krew (still minting)

**Comment by MillHaus33** [comment]
@Karmeleons 
image
looks like your pr is updating all these can you only add/update the ones you want

**Comment by Karmeleons** [comment]
@MillHaus33 Seems like I'm stuck in this endless loop where it's making me merge all collections with each commit. How do I just revert to an earlier commit?

**Pull request closed without merging**
