### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ArtsyGrims**

### CODE REVIEW

**Comment by chrisconfirm** [comment]
please check those id. i cannot open them atm, maybe wrong ids?

**Comment by ArtsyGrims** [comment]
I'll check it for you and resubmit - thanks for the heads up. Sent from my iPhoneOn 11 May 2023, at 20:13, chrisconfirm ***@***.***> wrote:﻿
please check those id. i cannot open them atm, maybe wrong ids?

**Comment by ArtsyGrims** [comment]
Thanks - still waiting for those latest inscription numbers clarification from the team at ordinalsbot. Sent from my iPhoneOn 12 May 2023, at 14:22, chrisconfirm ***@***.***> wrote:﻿
@ArtsyGrims i am closing this pull request for the moment. feel free to reopen this pr as soon as you have edited the inscription ids in the inscriptions.json here. thank you for your understanding.

**Comment by ArtsyGrims** [comment]
Side question Chris, is it possible to add a dev royalty % into the trades? Sent from my iPhoneOn 12 May 2023, at 14:22, chrisconfirm ***@***.***> wrote:﻿
@ArtsyGrims i am closing this pull request for the moment. feel free to reopen this pr as soon as you have edited the inscription ids in the inscriptions.json here. thank you for your understanding.

**Comment by chrisconfirm** [comment]
side question concerning royalties anwer: it is currently not possible to add royalties.

**Pull request closed without merging**
