### PR TITLE
Ordinal Phunks

### PR DESCRIPTION
**Pull request by The-Inscriptor**
New collection. Ordinal P**h**unks. Not a fake project, but follow up to Etherum parody project CryptoPhunks.

### CODE REVIEW

**Comment by The-Inscriptor** [comment]
Hello! Is everything all right with files I commited?

**Comment by utxo-detective** [comment]
> Hello! Is everything all right with files I commited?

Yes! We were just adding ci pipelines so we can validate everything. When they pass, we'll merge

**Comment by MillHaus33** [comment]
> Hello! Is everything all right with files I commited?

trailing comma seems to have been causing issue. also adding a website_link placeholder

**Comment by The-Inscriptor** [comment]
Cool. Thank you very much!

**Pull request merged**
