### PR TITLE
revert test file name and formatting

### PR DESCRIPTION
**Pull request by razr22**
replaced file contents with exact contents in the main branch. Reverted file name back to test_colllections.py

### CODE REVIEW

**Comment by Muhammadsetiobudi** [comment]
Why

**Comment by Muhammadsetiobudi** [comment]
I don't understand

**Comment by Muhammadsetiobudi** [comment]
you have a telegram for me to contact

**Comment by bitrabbit1** [comment]
[Update inscriptions.json](https://github.com/ordinals-wallet/ordinals-collections/pull/2452/commits/f185425949a0a39a73587ccc9df1e24a401fca96)

**Pull request closed without merging**
