### PR TITLE
Create inscriptions.json

### PR DESCRIPTION
**Pull request by DEALwithitDEV**

### CODE REVIEW

**Comment by chrisconfirm** [comment]
@DEALwithitDEV please see this version of your json
[inscriptions.json.txt](https://github.com/ordinals-wallet/ordinals-collections/files/12331698/inscriptions.json.txt)
i have replaced 
```javascript
",
}
``` 
with
```javascript
"
}
```
@utxo-detective does ow allow https in trait section? example line 3307
```javascript 
{
"trait_type": "SATOSHI LINK",
"value": "https://ordinals.com/sat/939164023633878",
}
```

**Comment by DEALwithitDEV** [comment]
ty

**Comment by DEALwithitDEV** [comment]
If putting a url is an issue, that's fine, I can remove them. This was a temporary solution until marketplaces figure out a way to display our double inscribed satoshis.

To my knowledge, we are the first collection to have double inscribed sats incorporated into our collection. I added the second cursed inscription info and sat links as traits for now.

**Comment by DEALwithitDEV** [comment]
So I just edited the inscriptions.json , now just have to get it in the right directory

**Comment by DEALwithitDEV** [comment]
appreciate the assistance guys

**Pull request closed without merging**
