### PR TITLE
Add smokin sarina, wahol sarina, backpage bitcoin from new account

### PR DESCRIPTION
**Pull request by SecondSarinaAccount**
I went ahead and created a new GitHub account because i couldn't figure out how to delete anything from the other account -- tlaine/smokinsarina

### CODE REVIEW

**Comment by MillHaus33** [comment]
image

you are closer. these need to go inside the collections folder

also, make sure your meta.json have placeholders for the links you dont have like "website_link": "" etc.

**Comment by SecondSarinaAccount** [comment]
> 

well, then I'm probably out of luck. I don.t have a way to open the json files to make corrections. - They were prepared for me.

**Comment by SecondSarinaAccount** [comment]
I'm shocked- I have a green check mark!

**Comment by SecondSarinaAccount** [comment]
Fuck yeah!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! --- you made me work for it but its all good now. -- gracias!

**Comment by MillHaus33** [comment]
congrats mate you made it

**Comment by utxo-detective** [comment]
> Fuck yeah!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! --- you made me work for it but its all good now. -- gracias!

lffffggg!!!!

image
image

**Comment by SecondSarinaAccount** [comment]
Yea!!!!!!!!!! :) 

⁣Get BlueMail for Android ​

**Pull request merged**
