### PR TITLE
adding our second doges collection

### PR DESCRIPTION
**Pull request by minidogenft**
thank you!

### CODE REVIEW

**Comment by chrisconfirm** [comment]
ordinal-mini-doges meta was created by pimax1?

**Comment by minidogenft** [comment]
yes its ok :) thank you

**Comment by chrisconfirm** [comment]
Hello @minidogenft , how do I see that this is your collection? Do you have a website or twitter account that is related to the colelction? Maybe we can get a comment from @Pimax1 as well

**Comment by Pimax1** [comment]
Hi there, we are the same account, dev account + official account

**Comment by minidogenft** [comment]
confirmed, and we will try to update only from minidogenft account if we ever need a new pr. thanks a lot

**Pull request merged**
