### PR TITLE
Create Pourteaux Anthology

### PR DESCRIPTION
**Pull request by pourteaux**
Errors fixed (hopefully)

### CODE REVIEW

**Comment by pourteaux** [comment]
This is a collection of early inscriptions from pourteaux

**Comment by chrisconfirm** [comment]
close pr. reason: contains cryptopunk copy.

**Comment by pourteaux** [comment]
Why was this closed? Inscription 89 is a licensed cryptopunk derivative (I own the actual ethereum cryptopunk and thus am licensed to make derivatives of it by Yuga Labs).

**Comment by pourteaux** [comment]
@chrisconfirm Why was this closed? Inscription 89 is not a "cryptopunk copy," it is a licensed cryptopunk derivative (I own the actual ethereum cryptopunk and thus am licensed to make derivatives of it by Yuga Labs).

**Pull request closed without merging**
