### PR TITLE
tpseto01

### PR DESCRIPTION
**Pull request by tpseto01**

### CODE REVIEW

**Comment by chrisconfirm** [comment]
closing pr. reason: pr outdated, /landscape-of-the-heart existing, contributed by @tpseto

**Comment by tpseto** [comment]
This is a collection of my works.
Because the notation is different from Magic Eden, I want to match it.
https://magiceden.io/ordinals/marketplace/landscape-of-the-heart

2023年5月7日(日) 4:51 chrisconfirm ***@***.***>:

**Comment by chrisconfirm** [comment]
closing pr. reason: not possible to update collection. please resubmit as pull request for /collections/landscape-of-the-heart/ so that we can update the collection. Thank you for your understanding.

**Comment by chrisconfirm** [comment]
close pr. outdated metadata. as stated above, we need a new pull request with the latest metadata if an update is needed. thank you for your understanding.

**Pull request closed without merging**
