### PR TITLE
Create deal-ordinals-bitcoin-benjies

### PR DESCRIPTION
**Pull request by DEALwithitDEV**

### CODE REVIEW

**Comment by utxo-detective** [comment]
The test failed, you need to add the `inscriptions.json` in the same pull request

`[deal-ordinals-bitcoin-benjies] No such file or directory (os error 2) collections/deal-ordinals-bitcoin-benjies/inscriptions.json`

**Comment by DEALwithitDEV** [comment]
I see the folder outside of the collections folder

**Comment by DEALwithitDEV** [comment]
ugh.... @utxo-detective I am fucking retarded clearly

**Comment by utxo-detective** [comment]
> ugh.... @utxo-detective I am fucking retarded clearly

embrace the left curve

**Comment by DEALwithitDEV** [comment]
Oh I always embrace it lmao- how TF do I get it in the right location in the directory now

**Pull request closed without merging**
