### PR TITLE
add ordinal checks

### PR DESCRIPTION
**Pull request by ordinalchecks**
add ordinal checks

### CODE REVIEW

**Comment by ordinalchecks** [comment]
@MillHaus33 appears this was closed but we are not listed, was there an issue w/ the PR?

**Comment by ordinalchecks** [comment]
@MillHaus33 moved the folder to collections and corrected name

**Comment by MillHaus33** [comment]
@ordinalchecks @coinyeezy i fixed there files but they have a bunch of invalid inscription numbers

**Comment by chrisconfirm** [comment]
i fixed the ids but we get "assert duplicates == 0 assert 100 == 0 Error " @MillHaus33

**Pull request merged**
