### PR TITLE
Listing Bitpidgey's Collection to Ordinals Wallet

### PR DESCRIPTION
**Pull request by samsagewize**
Wanting to Sumbit my Bitpidgey's Collection to Ordinals Wallet! Thank You

### CODE REVIEW

**Comment by chrisconfirm** [comment]
@samsagewize please note the directory /collections/your-collection-name-slug for next time. i have corrected it now. will be merged soon.

**Comment by samsagewize** [comment]
Thank you for that, just learning now how to submit! Much love and appreciate the help!

**Comment by samsagewize** [comment]
how can i fix this?

**Comment by samsagewize** [comment]
@chrisconfirm let me know what else i can do, thank you

**Comment by chrisconfirm** [comment]
I haven't found the error yet... and opening a new pr did not help either... please let me investigate some more but it may take some time. Thank you for your patience.

**Comment by samsagewize** [comment]
no worriessss

**Comment by chrisconfirm** [comment]
@utxo-detective can you help us out here? i can't find what's wrong. check is giving the following error message: 
_failures:_
---- test::valid_collections stdout ----
[bitpidgeys]  invalid length: 0

**Comment by samsagewize** [comment]
Bitpidgey's    - maybe the way its written gonna check on the format soon
thank you for the email

**Comment by samsagewize** [comment]
Screenshot 2023-08-30 091038

saw the error and fixed it not sure why its still giving me a error! trying to figure it out and navigate vi github, let me know if you can solve it been trying all morning lol! you can always dm me on twitter : @samsagewize

**Comment by chrisconfirm** [comment]
it works now! i have finally identified the problem, it was _"inscription_icon": ""_
the checkout is expecting a value for the coverimage there so i inserted the id of one of the bitpidgeys.

**Comment by chrisconfirm** [comment]
Thank you for your patience.

**Comment by samsagewize** [comment]
WOW THANK YOU SO MUCH FOR YOUR HELP!!! Can't Wait to see them in OW!! if i add more Bitpidgey's Just update the Inscription.json file correct?

**Comment by samsagewize** [comment]
Thank you so much for listing us ! super grateful! 

is it possible to add these to the collection as well ?, can't edit the file on my side


  {
    "id": "f954cb236f95066e63c43c27cbf5dadf76d4ae83193b865abee4c1f1964e334ci0",
    "meta": {
      "name": "BitPidgey #21"
    }
  },
  {
    "id": "2e691569c7c6fe77cf68583532fc14ac916b05e17ac3d7c5ac2742875b2fd9d1i0",
    "meta": {
      "name": "BitPidgey #22"
    }
  },
  {
    "id": "ea81d4ccd408024afa7760f283f81098b72716b0c1de59c2c7b127665db79093i0",
    "meta": {
      "name": "BitPidgey #23"
    }
  }
]

Those were the ones i put out yesterday and gave away!  Thanks in Advance! 🙏

**Comment by samsagewize** [comment]
> Thank you for your patience.

Thank You!! is it possible to continue adding to the collection? just curious

**Pull request merged**
