### PR TITLE
Update BitPunks Meta Data

### PR DESCRIPTION
**Pull request by NGAiYeah**

### CODE REVIEW

**Comment by chrisconfirm** [comment]
close. reason: relation of collection to user is unclear. see pr #1857 opened by the same user for Bitamigos and pr #1803 for BitPunks

**Comment by NGAiYeah** [comment]
So how can i update meta data for BitPunks? Delete all and pull new request?

**Comment by chrisconfirm** [comment]
see above. please show reference that you this is your collection. i can not check all inscriptions one by one so please help and establish your connection to the collection. Thank you for your understanding.

**Comment by NGAiYeah** [comment]
https://bitpunks.io/Home/ReadMe

**Comment by NGAiYeah** [comment]
At the bottom of the official website: "HEY CHRIS THIS IS MY COLLECTION", thanks!

**Comment by chrisconfirm** [comment]
see pr #2382

**Pull request closed without merging**
