### PR TITLE
Palindromes Collection Update 2023-08-16

### PR DESCRIPTION
**Pull request by ZedZeroth**
Thanks :)

### CODE REVIEW

**Review by chrisconfirm — APPROVED** [review]
this update is improving on the formatting and is adding the remaining of the 383 inscriptions to the inscriptions.json. this is in line with the supply given in the existing meta.json description.

**Comment by ZedZeroth** [comment]
Sorry, are you asking me to change something? Thanks

**Comment by chrisconfirm** [comment]
no i just approved the changes as a note. please have patience the maintainer will still need to resolve any conflicts there may be.

**Comment by ZedZeroth** [comment]
Great thank you

**Comment by utxo-detective** [comment]
Plz resolve conflicts

**Comment by ZedZeroth** [comment]
Hi, thanks for getting back to me but I don't understand what the conflicts are? I asked if something needed changing 5 days ago but chrisconfirm said no. I can make changes now if you can clarify the problem? Thanks

**Comment by ZedZeroth** [comment]
My new files should be valid JSON with the required properties? Thanks

**Comment by chrisconfirm** [comment]
i look into it.

**Comment by ZedZeroth** [comment]
Thanks

**Comment by chrisconfirm** [comment]
should be fine now, sync to website may take some time, please let us know if all is ok. Thank you for your patience.

**Comment by ZedZeroth** [comment]
Great thank you very much :)

**Comment by ZedZeroth** [comment]
"sync to website may take some time" Could I please confirm does this mean hours or days? Just wondering how often I should check whether it's synced. Thanks

**Pull request merged**
