### PR TITLE
Add Ordinal Greeks collection

### PR DESCRIPTION
**Pull request by reardencode**

### CODE REVIEW

**Comment by reardencode** [comment]
not sure why the build is failing. it says there's a duplicate, but I can't find one in this collection or any other.

**Comment by reardencode** [comment]
Hmm, bitcoindigits is listing `88` @ `53612bc8bac997d4962ef69d92ce8514155aa769d41b2fcc8ea73263bcf093f9i0`, but that's rightfully part of the greeks collection.

**Comment by reardencode** [comment]
@MillHaus33 Do you have a process for handling such a conflict? I inscribed that `88` for the creator of the Ordinal Greeks collection, but someone else has added it to another collection so our PR fails validation.

**Comment by reardencode** [comment]
Removed 88 from bitcoindigits to make this PR pass validation.

**Comment by benbuschmann** [comment]
Inscriptions can only be part of one collection? Why?

**Pull request merged**
