### PR TITLE
Create Multifaceted Tokyo

### PR DESCRIPTION
**Pull request by magcinephoto**

### CODE REVIEW

**Comment by MillHaus33** [comment]
please follow meta standard

**Comment by magcinephoto** [comment]
@MillHaus33 
Thanks for your comment.
Maybe the indent is different, so I fixed.
Is there any problem?

**Comment by MillHaus33** [comment]
use trait type and value instead of description

**Comment by magcinephoto** [comment]
@MillHaus33 
Oh thanks, I fixed it. Please check it out🙇‍♂️

**Pull request merged**
