### PR TITLE
refresh

### PR DESCRIPTION
**Pull request by mihasi1**
I didn’t know how to update the logo collection. It has not been updated on ordinalswallet.com.

### CODE REVIEW

**Comment by mihasi1** [comment]
Bitcordinals collection is not mine. When I made the fork, it was in synchronization. So I corrected it

**Comment by mihasi1** [comment]
There was a bug in Bitcordinals

**Comment by mihasi1** [comment]
How to update data on ordinalswallet.com after editing a collection in git?

**Comment by chrisconfirm** [comment]
close pr. reason: @mihasi1 is needlessly updating files by another uploader. and the second issue adresses in this pr, his own logo collection, is waiting for sync with the website. This issue does not need an inscription update. 
@mihasi1 please have patience for the website to sync with the repo. 
next time, please open one pull request for each issue/collection, and not multiple in one pr. thank you for your understanding.

**Pull request closed without merging**
