### PR TITLE
/ordinal-nouns/meta.json supply 51

### PR DESCRIPTION
**Pull request by chrisconfirm**
correcting wrong supply number, see pr #1978 by @skyrover7

### CODE REVIEW

**Comment by skyrover7** [comment]
@chrisconfirm still seeing the same issue on the collection page. you'll note the supply and the inscription range are not matching the data that was provided in the collection and meta json

image

**Comment by skyrover7** [comment]
@chrisconfirm @MillHaus33 any update here? still can't see the correct details on the page

**Comment by chrisconfirm** [comment]
@MillHaus33 can you see what the problem is? 

-->the meta.json says supply=51 
https://github.com/ordinals-wallet/ordinals-collections/blob/main/collections/ordinal-nouns/meta.json

-->but the collection page is showing supply=26, even after 2 weeks. 
https://ordinalswallet.com/collection/ordinal-nouns

how to solve this?

**Comment by MillHaus33** [comment]
check now

**Comment by skyrover7** [comment]
@MillHaus33 thank you for that! looks good now

**Pull request merged**
