### PR TITLE
Update honeybadgers

### PR DESCRIPTION
**Pull request by spencerrichardhenry**
Honey badgers needs to be updated now that all 10k are inscribed!

### CODE REVIEW

**Comment by spencerrichardhenry** [comment]
Having a hard time understanding what failed about the tests. Can you explain? thx!

**Comment by chrisconfirm** [comment]
it says that it found 1 duplicate inscription id. can you please check?

**Comment by spencerrichardhenry** [comment]
Hmm, the error states "f1912230294125dba7d06b9f116f374dbfb91eb95dd5a87c593b1b0f522d8419i0", but there's only one occurence of that string

**Comment by spencerrichardhenry** [comment]
Ah, I think it might be mad because I left an empty meta object. Guess I'll populate that info - was hoping to get it up today and flesh it out later.

**Comment by spencerrichardhenry** [comment]
Found the dupe. I modified the test like this in order to have the dupe id printed out, in case you'd like to adopt the change @chrisconfirm 

def test_uniqueness():
   ....
      duplicates = len(all_inscription_ids) - len(set(all_inscription_ids))
      if duplicates > 0:
        for inscription_id in set(inscriptions):
            if all_inscription_ids.count(inscription_id) > 1:
                print(f"Duplicate id: inscription_id")
                break
      assert duplicates == 0

**Comment by spencerrichardhenry** [comment]
Any way we can get this merged before monday? Thanks!

**Comment by spencerrichardhenry** [comment]
@chrisconfirm  anything for me to do here?

**Comment by spencerrichardhenry** [comment]
cc @MillHaus33 can this get approved please?

**Pull request merged**
