### PR TITLE
Pokemon Emerald by Ordinal Pokemon

### PR DESCRIPTION
**Pull request by OrdProfessorOak**

### CODE REVIEW

**Comment by MillHaus33** [comment]
are all of these your collections? can you resolve conflicts?

**Comment by OrdProfessorOak** [comment]
> are all of these your collections? can you resolve conflicts?

Resolving conflicts now. :D

**Comment by OrdProfessorOak** [comment]
I completed the meta update for all 3 collections.

**Comment by OrdProfessorOak** [comment]
@MillHaus33 Could you please approve this pull request?

**Pull request closed without merging**
