### PR TITLE
update ordinal noun collection 51

### PR DESCRIPTION
**Pull request by skyrover7**

### CODE REVIEW

**Comment by skyrover7** [comment]
@genlivre please merge 🙏🏾

**Comment by skyrover7** [comment]
@chrisconfirm i see that this has been merged and closed but the collection on the site has not updated. Please let me know

https://ordinalswallet.com/collection/ordinal-nouns

**Comment by chrisconfirm** [comment]
is it ok now?

**Comment by skyrover7** [comment]
@chrisconfirm does not look like it. you can see the supply is 51 in the `meta.json` yet still showing 26 on the collection page

**Pull request merged**
