### PR TITLE
The Dan Files

### PR DESCRIPTION
**Pull request by droplister**
Please add this to your repository.

Not included in this PR are the JSON files I originally inscribed to "collect" these inscriptions. The index is here:
https://ordinals.com/inscription/677e9b18641f86b22bea3d324c0c50dd498507514f887818a21f2ff7d81b1e9fi0

### CODE REVIEW

**Comment by droplister** [comment]
This is failing on the basis of uniqueness, but all of this are the original collection by the creator (me).

The "Numberwangs" in my JSON file have been curated by `bitcoindigits` but not issued by them.

**Comment by droplister** [comment]
@MillHaus33 Please consider reviewing.

**Comment by droplister** [comment]
@MillHaus33  Please don't overlook this due to the red 'x'.

**Comment by droplister** [comment]
image

**Comment by chrisconfirm** [comment]
assert duplicates == 0
E         assert 97 == 0 
@MillHaus33

**Comment by chrisconfirm** [comment]
this will take some more time to check. i guess these are yours, but then there are some other random ones which i did not have time to research yet. thank you for your patience.

**Comment by chrisconfirm** [comment]
@droplister it is difficult to check all of this. i can see your "proof" inscriptions 952 and 953 for bitblocks and dan-files. but these only amount to 20 inscriptions in total. please comment on the bigger supply of 65 in this pull request. are there more "proof" inscriptions i am missing? thank you for your understanding.

**Comment by droplister** [comment]
The Dan Files is the collection, there are 10 subcollections or series.

Inscription 953 is an index:
https://ordinals.com/inscription/677e9b18641f86b22bea3d324c0c50dd498507514f887818a21f2ff7d81b1e9fi0

It links to these JSONs which specify what's in the 10 subcollections.
https://ordinals.com/inscription/76a7fbd6b8f11f7f8fe6b503ebc99a6a9914b5fd5d0034735855e00460e1dda1i0
https://ordinals.com/inscription/4cc1bfc7f432a9f8eda4e62496eeded638245c9e48c619e49bd51fe1e160f25ci0
https://ordinals.com/inscription/aa52bf43287c659995296fe23a4c6e094f709b256f451509a1dbf294f034167fi0
https://ordinals.com/inscription/1fc10d585ddf64a0d09eb7f34744f5435e11c7fc1e458bc49ec2e33d7f8cc7c7i0
https://ordinals.com/inscription/8a553a300dc0c6837283647fb8f66f70effb6ee283d14c48e87420cd9fde180ai0
https://ordinals.com/inscription/b1f8b49eb230b08ca6a4c9b735ab9701369caace5df0157465f1dc59aa48247ci0
https://ordinals.com/inscription/f3809553e7badee2bd042eca5163a925d768a1a5b589e62228ada685da3d8c52i0
https://ordinals.com/inscription/6b16c15179a41a94465ed99d787804520c028282332f0f725a1efbfa3195cdf6i0
https://ordinals.com/inscription/d27a0373684f6bbeadc8a85a36bb5305a4f60bc5f926f40c03576311c7f8dcabi0
https://ordinals.com/inscription/5450c67668d4aeef332fb344df9b7277c80f280691df7a2ca9775974c6c99043i0

**Comment by chrisconfirm** [comment]
close pr. can not be merged. reason: inscription 668 is nsfw.

**Pull request closed without merging**
