### PR TITLE
Add Ordinal Meerkats Country Club

### PR DESCRIPTION
**Pull request by MMCCSolana**

### CODE REVIEW

**Comment by MMCCSolana** [comment]
Hey Fam, do you know why this is erroring? It is showing duplicates, but none exist.

**Comment by MMCCSolana** [comment]
Thanks @chrisconfirm 

Did ALL of the inscriptions get put in? I think the website is only showing some of them

**Comment by MMCCSolana** [comment]
I believe our supply is 713 and ordinals range is #550025-1112815

Screen Shot 2023-05-20 at 5 56 23 PM

**Comment by chrisconfirm** [comment]
@MillHaus33 how to fix updating supply according to meta.json
meta.json: supply=713, collections page: supply=204 ...

**Pull request merged**
