### PR TITLE
Update inscriptions.json

### PR DESCRIPTION
**Pull request by DEALwithitDEV**

### CODE REVIEW

**Comment by DEALwithitDEV** [comment]
@chrisconfirm thank you, it's not that intuitive to be able to edit the path like that, appreciate you spelling ti out for me.

I just did pull requests for both .json files, lmk if I need to correct it plz

**Comment by DEALwithitDEV** [comment]
Why did this fail? any idea? @chrisconfirm ?

**Comment by utxo-detective** [comment]
`No such file or directory (os error 2) collections/deal-ordinals-bitcoin-benjies/meta.json`

**Comment by DEALwithitDEV** [comment]
right I'm trying to edit the path. so that it will exist there.

**Comment by DEALwithitDEV** [comment]
Why am I still fucking this up @chrisconfirm @utxo-detective

**Comment by chrisconfirm** [comment]
@DEALwithitDEV you are not, no worries. a conflict within the file system needs to be resolved first.
--> old version of /deal-ordinals-bitcoin-benjies is not valid and needs to be manually deleted from the repo
--> after that it should work. It will be easiest if the maintainer does it for you. Please be patient.

**Comment by DEALwithitDEV** [comment]
I give up, I have no idea what I'm missing here

**Pull request closed without merging**
