### PR TITLE
Created new collection for spliffy

### PR DESCRIPTION
**Pull request by OrdinalsisDope**
Added meta and inscriptions for new collection

### CODE REVIEW

**Comment by chrisconfirm** [comment]
is currently part of btc-frens. take out respective ids of btc-frens and make own collection?

**Comment by chrisconfirm** [comment]
close pr. reason: unclear if ids belong to btc-frens or new collection here.

**Comment by OrdinalsisDope** [comment]
Yes it relates to bc frens we are good fam

**Comment by chrisconfirm** [comment]
please comment with a reference by https://twitter.com/btcordinal .
It is not clear why these inscriptions should be taken out of btc-frens and put into their own collection.

**Comment by OrdinalsisDope** [comment]
They have to stay in btc-frens .. the merge request I did was very long
time ago when BTC machine still didn’t have the idea of making a collection
with all the collabs.. anyway summarizing you don’t need to do anything
anymore here.. these artifacts are good in BTC-Frens

**Comment by chrisconfirm** [comment]
ok thank you for clarification. will stay in btc-frens collection then.

**Pull request closed without merging**
