### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Sopan1000000000000**

### CODE REVIEW

**Comment by Sopan1000000000000** [comment]
I dont know if I did it right? This is a pull request to include the "Che on Bitcoin" collection in Ordinals Collections.

**Comment by chrisconfirm** [comment]
yes your uploads seem correct, i only updated the formatting.

**Comment by Sopan1000000000000** [comment]
Hi. Thank you! What do I do now? Am I done? Will my collection be on display in Ordinals Wallet?

**Comment by Sopan1000000000000** [comment]
> yes your uploads seem correct, i only updated the formatting.

Hi! Thank you! What do I do now? Am I done? Will my collection be on display  in Ordinals Wallet, and when if so?

**Comment by Sopan1000000000000** [comment]
Somebody can help me? Im here for the first time.

**Pull request merged**
